export const CATEGORIES = {
    ANIMALS: { emoji: "🐾", color: "#FF6B35", words: ["pig", "dog", "cat", "lion", "zebra", "bear", "chicken", "duck", "sheep", "goat"] },
    HEALTH: { emoji: "🏥", color: "#E63946", words: ["flu", "rest", "germs", "sick", "bed", "fever", "pain", "nurse", "doctor"] },
    PLACES: { emoji: "🏠", color: "#457B9D", words: ["house", "farm", "city", "town", "park", "school", "mall", "hospital", "street", "bank"] },
    FAMILY: { emoji: "👨‍👩‍👧‍👦", color: "#E9C46A", words: ["mom", "dad", "sister", "brother", "aunt", "uncle", "me", "cousin", "baby", "family"] },
    SCHOOL: { emoji: "📚", color: "#2A9D8F", words: ["boy", "girl", "teacher", "student", "pencil", "eraser", "table", "chair", "board", "book"] },
    OCEAN: { emoji: "🌊", color: "#0077B6", words: ["beach", "map", "tree", "sand", "chest", "ship", "fish", "pirate", "ocean", "sky"] },
    SPORTS: { emoji: "⚽", color: "#F4A261", words: ["sport", "ball", "run", "climb", "hit", "kick", "team", "soccer", "tennis", "jump"] },
    FOOD: { emoji: "🍎", color: "#E76F51", words: ["apple", "milk", "salt", "fruit", "egg", "protein", "drink", "carrot", "grain", "cheese"] },
    DINOSAUR: { emoji: "🦕", color: "#6A4C93", words: ["head", "horn", "leg", "tail", "neck", "teeth", "bones", "wings", "spikes", "claws"] },
    PLANTS: { emoji: "🌱", color: "#606C38", words: ["seed", "plant", "flower", "roots", "leaves", "petals", "bloom", "grow", "water", "soil"] },
};

export type Hint = { emoji: string; image: string };

export const HINTS: Record<string, Hint> = {
    pig: { emoji: "🐷", image: "/images/words/pig.png" }, dog: { emoji: "🐕", image: "/images/words/dog.png" }, cat: { emoji: "🐱", image: "/images/words/cat.png" }, lion: { emoji: "🦁", image: "/images/words/lion.png" }, zebra: { emoji: "🦓", image: "/images/words/zebra.png" }, bear: { emoji: "🐻", image: "/images/words/bear.png" }, chicken: { emoji: "🐔", image: "/images/words/chicken.png" }, duck: { emoji: "🦆", image: "/images/words/duck.png" }, sheep: { emoji: "🐑", image: "/images/words/sheep.png" }, goat: { emoji: "🐐", image: "/images/words/goat.png" },
    flu: { emoji: "🤒", image: "/images/words/flu.png" }, rest: { emoji: "😴", image: "/images/words/rest.png" }, germs: { emoji: "🦠", image: "/images/words/germs.png" }, sick: { emoji: "🤢", image: "/images/words/sick.png" }, bed: { emoji: "🛏️", image: "/images/words/bed.png" }, fever: { emoji: "🌡️", image: "/images/words/fever.png" }, pain: { emoji: "🤕", image: "/images/words/pain.png" }, nurse: { emoji: "👩‍⚕️", image: "/images/words/nurse.png" }, doctor: { emoji: "👨‍⚕️", image: "/images/words/doctor.png" },
    house: { emoji: "🏠", image: "/images/words/house.png" }, farm: { emoji: "🚜", image: "/images/words/farm.png" }, city: { emoji: "🏙️", image: "/images/words/city.png" }, town: { emoji: "🏘️", image: "/images/words/town.png" }, park: { emoji: "🌳", image: "/images/words/park.png" }, school: { emoji: "🏫", image: "/images/words/school.png" }, mall: { emoji: "🛍️", image: "/images/words/mall.png" }, hospital: { emoji: "🏥", image: "/images/words/hospital.png" }, street: { emoji: "🛣️", image: "/images/words/street.png" }, bank: { emoji: "🏦", image: "/images/words/bank.png" },
    mom: { emoji: "👩", image: "/images/words/mom.png" }, dad: { emoji: "👨", image: "/images/words/dad.png" }, sister: { emoji: "👧", image: "/images/words/sister.png" }, brother: { emoji: "👦", image: "/images/words/brother.png" }, aunt: { emoji: "👩‍🦰", image: "/images/words/aunt.png" }, uncle: { emoji: "👨‍🦱", image: "/images/words/uncle.png" }, me: { emoji: "🙋", image: "/images/words/me.png" }, cousin: { emoji: "🧑", image: "/images/words/cousin.png" }, baby: { emoji: "👶", image: "/images/words/baby.png" }, family: { emoji: "👨‍👩‍👧‍👦", image: "/images/words/family.png" },
    boy: { emoji: "👦", image: "/images/words/boy.png" }, girl: { emoji: "👧", image: "/images/words/girl.png" }, teacher: { emoji: "👩‍🏫", image: "/images/words/teacher.png" }, student: { emoji: "🎒", image: "/images/words/student.png" }, pencil: { emoji: "✏️", image: "/images/words/pencil.png" }, eraser: { emoji: "🧽", image: "/images/words/eraser.png" }, table: { emoji: "🪑", image: "/images/words/table.png" }, chair: { emoji: "💺", image: "/images/words/chair.png" }, board: { emoji: "📋", image: "/images/words/board.png" }, book: { emoji: "📖", image: "/images/words/book.png" },
    beach: { emoji: "🏖️", image: "/images/words/beach.png" }, map: { emoji: "🗺️", image: "/images/words/map.png" }, tree: { emoji: "🌲", image: "/images/words/tree.png" }, sand: { emoji: "⏳", image: "/images/words/sand.png" }, chest: { emoji: "📦", image: "/images/words/chest.png" }, ship: { emoji: "🚢", image: "/images/words/ship.png" }, fish: { emoji: "🐟", image: "/images/words/fish.png" }, pirate: { emoji: "🏴‍☠️", image: "/images/words/pirate.png" }, ocean: { emoji: "🌊", image: "/images/words/ocean.png" }, sky: { emoji: "☁️", image: "/images/words/sky.png" },
    sport: { emoji: "🏅", image: "/images/words/sport.png" }, ball: { emoji: "⚽", image: "/images/words/ball.png" }, run: { emoji: "🏃", image: "/images/words/run.png" }, climb: { emoji: "🧗", image: "/images/words/climb.png" }, hit: { emoji: "🥊", image: "/images/words/hit.png" }, kick: { emoji: "🦶", image: "/images/words/kick.png" }, team: { emoji: "👥", image: "/images/words/team.png" }, soccer: { emoji: "⚽", image: "/images/words/soccer.png" }, tennis: { emoji: "🎾", image: "/images/words/tennis.png" }, jump: { emoji: "🤸", image: "/images/words/jump.png" },
    apple: { emoji: "🍎", image: "/images/words/apple.png" }, milk: { emoji: "🥛", image: "/images/words/milk.png" }, salt: { emoji: "🧂", image: "/images/words/salt.png" }, fruit: { emoji: "🍇", image: "/images/words/fruit.png" }, egg: { emoji: "🥚", image: "/images/words/egg.png" }, protein: { emoji: "💪", image: "/images/words/protein.png" }, drink: { emoji: "🥤", image: "/images/words/drink.png" }, carrot: { emoji: "🥕", image: "/images/words/carrot.png" }, grain: { emoji: "🌾", image: "/images/words/grain.png" }, cheese: { emoji: "🧀", image: "/images/words/cheese.png" },
    head: { emoji: "🦕", image: "/images/words/head.png" }, horn: { emoji: "🦏", image: "/images/words/horn.png" }, leg: { emoji: "🦿", image: "/images/words/leg.png" }, tail: { emoji: "🐊", image: "/images/words/tail.png" }, neck: { emoji: "🦒", image: "/images/words/neck.png" }, teeth: { emoji: "🦷", image: "/images/words/teeth.png" }, bones: { emoji: "🦴", image: "/images/words/bones.png" }, wings: { emoji: "🪽", image: "/images/words/wings.png" }, spikes: { emoji: "🔱", image: "/images/words/spikes.png" }, claws: { emoji: "🐾", image: "/images/words/claws.png" },
    seed: { emoji: "🌰", image: "/images/words/seed.png" }, plant: { emoji: "🌿", image: "/images/words/plant.png" }, flower: { emoji: "🌸", image: "/images/words/flower.png" }, roots: { emoji: "🌳", image: "/images/words/roots.png" }, leaves: { emoji: "🍃", image: "/images/words/leaves.png" }, petals: { emoji: "🌺", image: "/images/words/petals.png" }, bloom: { emoji: "🌷", image: "/images/words/bloom.png" }, grow: { emoji: "📈", image: "/images/words/grow.png" }, water: { emoji: "💧", image: "/images/words/water.png" }, soil: { emoji: "🟤", image: "/images/words/soil.png" },
};

export const DIFFICULTY = {
    EASY: { label: "Fácil", stars: 1, timeLimit: 0, showHint: true, showFirst: true, multiplier: 1, color: "#2A9D8F", wordCount: 6, desc: "Emoji + letra · Sin tiempo" },
    MEDIUM: { label: "Medio", stars: 2, timeLimit: 30, showHint: true, showFirst: false, multiplier: 2, color: "#E9C46A", wordCount: 8, desc: "Solo emoji · 30s/palabra" },
    HARD: { label: "Difícil", stars: 3, timeLimit: 15, showHint: false, showFirst: false, multiplier: 3, color: "#E76F51", wordCount: 10, desc: "Solo categoría · 15s/palabra" }
};
