import type { SubjectWorld } from "./types";

export const MATH_EXAM_WORLD: SubjectWorld = {
    id: "math",
    title: "Matemáticas",
    emoji: "🔢",
    color: "#E76F51",
    description: "Notación desarrollada, valor posicional, comparación y problemas",
    levels: [
        {
            id: "notacion-desarrollada",
            title: "Notación Desarrollada",
            emoji: "🧩",
            description: "Descomponer números en millares, centenas, decenas y unidades",
            color: "#E76F51",
            questions: [
                {
                    id: "ma-01",
                    levelId: "notacion-desarrollada",
                    questionType: "multiple_choice",
                    questionText: "¿Cuál es la notación desarrollada de 1,234?",
                    points: 10,
                    options: [
                        "1000 + 200 + 30 + 4",
                        "1000 + 230 + 4",
                        "1200 + 34",
                        "1000 + 200 + 34",
                    ],
                    correctAnswer: "1000 + 200 + 30 + 4",
                },
                {
                    id: "ma-02",
                    levelId: "notacion-desarrollada",
                    questionType: "numeric_input",
                    questionText: "¿Qué número es 3000 + 400 + 50 + 7?",
                    points: 10,
                    correctAnswer: "3457",
                    hint: "Suma cada valor posicional",
                },
                {
                    id: "ma-03",
                    levelId: "notacion-desarrollada",
                    questionType: "numeric_input",
                    questionText: "¿Qué número es 5000 + 600 + 20 + 1?",
                    points: 10,
                    correctAnswer: "5621",
                },
                {
                    id: "ma-04",
                    levelId: "notacion-desarrollada",
                    questionType: "multiple_choice",
                    questionText: "¿Cuál es la notación desarrollada de 4,506?",
                    points: 10,
                    options: [
                        "4000 + 500 + 6",
                        "4000 + 500 + 60",
                        "4000 + 50 + 6",
                        "400 + 500 + 6",
                    ],
                    correctAnswer: "4000 + 500 + 6",
                },
                {
                    id: "ma-05",
                    levelId: "notacion-desarrollada",
                    questionType: "numeric_input",
                    questionText: "¿Qué número es 2000 + 300 + 10 + 8?",
                    points: 10,
                    correctAnswer: "2318",
                },
                {
                    id: "ma-06",
                    levelId: "notacion-desarrollada",
                    questionType: "multiple_choice",
                    questionText: "¿Cuál es la notación desarrollada de 7,090?",
                    points: 10,
                    options: [
                        "7000 + 90",
                        "7000 + 900",
                        "7000 + 9",
                        "700 + 90",
                    ],
                    correctAnswer: "7000 + 90",
                },
                {
                    id: "ma-07",
                    levelId: "notacion-desarrollada",
                    questionType: "numeric_input",
                    questionText: "¿Qué número es 8000 + 100 + 40 + 3?",
                    points: 10,
                    correctAnswer: "8143",
                },
            ],
        },
        {
            id: "valor-posicional",
            title: "Valor Posicional",
            emoji: "🏗️",
            description: "Unidades de millar, centenas, decenas y unidades",
            color: "#6A4C93",
            questions: [
                {
                    id: "ma-08",
                    levelId: "valor-posicional",
                    questionType: "multiple_choice",
                    questionText: "En el número 3,456, ¿en qué posición está el 3?",
                    points: 10,
                    options: [
                        "Unidades de millar",
                        "Centenas",
                        "Decenas",
                        "Unidades",
                    ],
                    correctAnswer: "Unidades de millar",
                },
                {
                    id: "ma-09",
                    levelId: "valor-posicional",
                    questionType: "multiple_choice",
                    questionText: "En el número 1,234, ¿cuál es el valor del 2?",
                    points: 10,
                    options: [
                        "200",
                        "2",
                        "20",
                        "2000",
                    ],
                    correctAnswer: "200",
                    hint: "El 2 está en la posición de las centenas",
                },
                {
                    id: "ma-10",
                    levelId: "valor-posicional",
                    questionType: "multiple_choice",
                    questionText: "En el número 5,678, ¿en qué posición está el 7?",
                    points: 10,
                    options: [
                        "Decenas",
                        "Unidades",
                        "Centenas",
                        "Unidades de millar",
                    ],
                    correctAnswer: "Decenas",
                },
                {
                    id: "ma-11",
                    levelId: "valor-posicional",
                    questionType: "numeric_input",
                    questionText: "¿Qué número tiene 4 unidades de millar, 3 centenas, 2 decenas y 5 unidades?",
                    points: 10,
                    correctAnswer: "4325",
                    hint: "4×1000 + 3×100 + 2×10 + 5",
                },
                {
                    id: "ma-12",
                    levelId: "valor-posicional",
                    questionType: "multiple_choice",
                    questionText: "En el número 9,012, ¿cuál es el valor del 0?",
                    points: 10,
                    options: [
                        "0 (no tiene valor porque es cero centenas)",
                        "100",
                        "10",
                        "1000",
                    ],
                    correctAnswer: "0 (no tiene valor porque es cero centenas)",
                },
                {
                    id: "ma-13",
                    levelId: "valor-posicional",
                    questionType: "numeric_input",
                    questionText: "¿Qué número tiene 6 unidades de millar, 0 centenas, 4 decenas y 8 unidades?",
                    points: 10,
                    correctAnswer: "6048",
                },
            ],
        },
        {
            id: "comparar-numeros",
            title: "Comparar Números",
            emoji: "⚖️",
            description: "Menor que, mayor que e igual que",
            color: "#457B9D",
            questions: [
                {
                    id: "ma-14",
                    levelId: "comparar-numeros",
                    questionType: "compare",
                    questionText: "Compara estos dos números",
                    points: 10,
                    comparePair: ["1700", "1500"],
                    correctAnswer: ">",
                    hint: "Mil setecientos es mayor que mil quinientos",
                },
                {
                    id: "ma-15",
                    levelId: "comparar-numeros",
                    questionType: "compare",
                    questionText: "Compara estos dos números",
                    points: 10,
                    comparePair: ["3000", "8000"],
                    correctAnswer: "<",
                    hint: "Tres mil es menor que ocho mil",
                },
                {
                    id: "ma-16",
                    levelId: "comparar-numeros",
                    questionType: "compare",
                    questionText: "Compara estos dos números",
                    points: 10,
                    comparePair: ["4000", "4000"],
                    correctAnswer: "=",
                    hint: "Cuatro mil es igual que cuatro mil",
                },
                {
                    id: "ma-17",
                    levelId: "comparar-numeros",
                    questionType: "compare",
                    questionText: "Compara estos dos números",
                    points: 10,
                    comparePair: ["2560", "2650"],
                    correctAnswer: "<",
                },
                {
                    id: "ma-18",
                    levelId: "comparar-numeros",
                    questionType: "compare",
                    questionText: "Compara estos dos números",
                    points: 10,
                    comparePair: ["7890", "7098"],
                    correctAnswer: ">",
                },
                {
                    id: "ma-19",
                    levelId: "comparar-numeros",
                    questionType: "compare",
                    questionText: "Compara estos dos números",
                    points: 10,
                    comparePair: ["5500", "5500"],
                    correctAnswer: "=",
                },
                {
                    id: "ma-20",
                    levelId: "comparar-numeros",
                    questionType: "multiple_choice",
                    questionText: "¿Qué signo se usa cuando el número de la izquierda es más grande?",
                    points: 10,
                    options: ["> (mayor que)", "< (menor que)", "= (igual que)", "+ (más)"],
                    correctAnswer: "> (mayor que)",
                },
            ],
        },
        {
            id: "problemas-razonados",
            title: "Problemas Razonados",
            emoji: "🧠",
            description: "Problemas de suma y resta con contexto",
            color: "#E9C46A",
            questions: [
                {
                    id: "ma-21",
                    levelId: "problemas-razonados",
                    questionType: "word_problem",
                    questionText: "Lee el problema y resuélvelo",
                    points: 10,
                    wordProblemData: {
                        problemText: "En la campaña de reciclaje, Sofía juntó 245 botellas y Mateo juntó 123 botellas. ¿Cuántas botellas juntaron en total entre los dos?",
                        operationOptions: ["Suma", "Resta"],
                        correctOperation: "Suma",
                        correctAnswer: "368",
                    },
                },
                {
                    id: "ma-22",
                    levelId: "problemas-razonados",
                    questionType: "word_problem",
                    questionText: "Lee el problema y resuélvelo",
                    points: 10,
                    wordProblemData: {
                        problemText: "En la biblioteca había 178 libros de cuentos. Si se prestaron 56 libros, ¿cuántos libros quedaron en la biblioteca?",
                        operationOptions: ["Suma", "Resta"],
                        correctOperation: "Resta",
                        correctAnswer: "122",
                    },
                },
                {
                    id: "ma-23",
                    levelId: "problemas-razonados",
                    questionType: "word_problem",
                    questionText: "Lee el problema y resuélvelo",
                    points: 10,
                    wordProblemData: {
                        problemText: "En una papelería, Ana compró 368 estampas y su hermana compró 247 estampas. ¿Cuántas estampas compraron en total entre las dos?",
                        operationOptions: ["Suma", "Resta"],
                        correctOperation: "Suma",
                        correctAnswer: "615",
                    },
                },
                {
                    id: "ma-24",
                    levelId: "problemas-razonados",
                    questionType: "word_problem",
                    questionText: "Lee el problema y resuélvelo",
                    points: 10,
                    wordProblemData: {
                        problemText: "En el salón había 195 colores. Si se repartieron 84 colores a los alumnos, ¿cuántos colores quedaron sin repartir?",
                        operationOptions: ["Suma", "Resta"],
                        correctOperation: "Resta",
                        correctAnswer: "111",
                    },
                },
                {
                    id: "ma-25",
                    levelId: "problemas-razonados",
                    questionType: "word_problem",
                    questionText: "Lee el problema y resuélvelo",
                    points: 10,
                    wordProblemData: {
                        problemText: "Pedro tenía 450 canicas y su amigo le regaló 230 más. ¿Cuántas canicas tiene Pedro ahora?",
                        operationOptions: ["Suma", "Resta"],
                        correctOperation: "Suma",
                        correctAnswer: "680",
                    },
                },
                {
                    id: "ma-26",
                    levelId: "problemas-razonados",
                    questionType: "word_problem",
                    questionText: "Lee el problema y resuélvelo",
                    points: 10,
                    wordProblemData: {
                        problemText: "En una tienda había 500 juguetes. Se vendieron 175. ¿Cuántos juguetes quedaron?",
                        operationOptions: ["Suma", "Resta"],
                        correctOperation: "Resta",
                        correctAnswer: "325",
                    },
                },
            ],
        },
    ],
};
