import type { SubjectWorld } from "./types";

export const SCIENCE_WORLD: SubjectWorld = {
    id: "science",
    title: "Ciencias y FCyE",
    emoji: "🌍",
    color: "#2A9D8F",
    description: "La basura, reciclaje, composta y cuidado del ambiente",
    levels: [
        {
            id: "la-basura",
            title: "La Basura",
            emoji: "🗑️",
            description: "Tipos de basura y diferencias",
            color: "#6A4C93",
            questions: [
                {
                    id: "sc-01",
                    levelId: "la-basura",
                    questionType: "multiple_choice",
                    questionText: "¿Qué es la basura?",
                    points: 10,
                    options: [
                        "Desechos que ya no podemos reutilizar: restos, descompuestos o que cumplieron su utilidad",
                        "Solo lo que tiramos en la cocina",
                        "Cualquier cosa que esté en el piso",
                        "Solo los juguetes rotos",
                    ],
                    correctAnswer: "Desechos que ya no podemos reutilizar: restos, descompuestos o que cumplieron su utilidad",
                },
                {
                    id: "sc-02",
                    levelId: "la-basura",
                    questionType: "multiple_choice",
                    questionText: "¿Cuál es la diferencia entre desecho y residuo?",
                    points: 10,
                    options: [
                        "Los residuos aún tienen algún uso, los desechos ya no",
                        "Son exactamente lo mismo",
                        "Los desechos son más grandes",
                        "Los residuos siempre son líquidos",
                    ],
                    correctAnswer: "Los residuos aún tienen algún uso, los desechos ya no",
                },
                {
                    id: "sc-03",
                    levelId: "la-basura",
                    questionType: "classify",
                    questionText: "Clasifica cada objeto en el bote correcto",
                    points: 10,
                    categories: [
                        { id: "organica", label: "Orgánica", emoji: "🟢", color: "#2A9D8F" },
                        { id: "inorganica", label: "Inorgánica", emoji: "⚪", color: "#6B7280" },
                        { id: "reciclable", label: "Reciclable", emoji: "🔵", color: "#457B9D" },
                    ],
                    classifyItems: [
                        { text: "Cáscara de plátano", emoji: "🍌", correctCategoryId: "organica" },
                        { text: "Botella de plástico", emoji: "🧴", correctCategoryId: "reciclable" },
                        { text: "Restos de comida", emoji: "🍽️", correctCategoryId: "organica" },
                        { text: "Lata de aluminio", emoji: "🥫", correctCategoryId: "reciclable" },
                        { text: "Hojas de árbol", emoji: "🍂", correctCategoryId: "organica" },
                        { text: "Plásticos y vidrios rotos", emoji: "🪟", correctCategoryId: "inorganica" },
                        { text: "Cartón", emoji: "📦", correctCategoryId: "reciclable" },
                        { text: "Metales oxidados", emoji: "🔩", correctCategoryId: "inorganica" },
                    ],
                },
                {
                    id: "sc-04",
                    levelId: "la-basura",
                    questionType: "true_false",
                    questionText: "La basura orgánica son restos de comida, papel, cartón, ramas y hojas que con el tiempo se descomponen",
                    points: 10,
                    correctAnswer: "Verdadero",
                },
                {
                    id: "sc-05",
                    levelId: "la-basura",
                    questionType: "true_false",
                    questionText: "La basura inorgánica se descompone rápidamente",
                    points: 10,
                    correctAnswer: "Falso",
                    hint: "Los objetos inorgánicos tardan mucho tiempo en desintegrarse",
                },
                {
                    id: "sc-06",
                    levelId: "la-basura",
                    questionType: "multiple_choice",
                    questionText: "¿Qué tipo de basura son los plásticos, vidrios y metales?",
                    points: 10,
                    options: [
                        "Inorgánica",
                        "Orgánica",
                        "Compostable",
                        "Natural",
                    ],
                    correctAnswer: "Inorgánica",
                },
            ],
        },
        {
            id: "tres-erres",
            title: "Las 3 R's",
            emoji: "♻️",
            description: "Reducir, Reutilizar y Reciclar",
            color: "#2A9D8F",
            questions: [
                {
                    id: "sc-07",
                    levelId: "tres-erres",
                    questionType: "match",
                    questionText: "Relaciona cada R con su definición",
                    points: 10,
                    matchPairs: [
                        { left: "Reducir", right: "Disminuir el consumo de recursos para generar menos basura" },
                        { left: "Reparar", right: "Arreglar productos para prolongar su vida útil" },
                        { left: "Reciclar", right: "Transformar materiales desechados en nuevos productos" },
                    ],
                },
                {
                    id: "sc-08",
                    levelId: "tres-erres",
                    questionType: "classify",
                    questionText: "¿A cuál de las 3 R's corresponde cada acción?",
                    points: 10,
                    categories: [
                        { id: "reducir", label: "Reducir", emoji: "📉", color: "#2A9D8F" },
                        { id: "reutilizar", label: "Reutilizar", emoji: "🔄", color: "#E9C46A" },
                        { id: "reciclar", label: "Reciclar", emoji: "♻️", color: "#457B9D" },
                    ],
                    classifyItems: [
                        { text: "Usar una botella como maceta", emoji: "🪴", correctCategoryId: "reutilizar" },
                        { text: "Fabricar papel reciclado con papel viejo", emoji: "📄", correctCategoryId: "reciclar" },
                        { text: "Usar menos bolsas de plástico", emoji: "🛍️", correctCategoryId: "reducir" },
                        { text: "Donar ropa que ya no usas", emoji: "👕", correctCategoryId: "reutilizar" },
                        { text: "Transformar latas en objetos nuevos", emoji: "🥫", correctCategoryId: "reciclar" },
                        { text: "Consumir menos productos desechables", emoji: "🚫", correctCategoryId: "reducir" },
                    ],
                },
                {
                    id: "sc-09",
                    levelId: "tres-erres",
                    questionType: "true_false",
                    questionText: "Reciclar consiste en transformar materiales desechados en nuevos productos",
                    points: 10,
                    correctAnswer: "Verdadero",
                },
                {
                    id: "sc-10",
                    levelId: "tres-erres",
                    questionType: "true_false",
                    questionText: "Reutilizar es lo mismo que tirar a la basura",
                    points: 10,
                    correctAnswer: "Falso",
                    hint: "Reutilizar es darle un nuevo uso a un objeto",
                },
                {
                    id: "sc-11",
                    levelId: "tres-erres",
                    questionType: "multiple_choice",
                    questionText: "¿Qué significa Reducir?",
                    points: 10,
                    options: [
                        "Disminuir el consumo de recursos para generar menos basura",
                        "Tirar todo lo que no usamos",
                        "Comprar más productos nuevos",
                        "Quemar la basura",
                    ],
                    correctAnswer: "Disminuir el consumo de recursos para generar menos basura",
                },
            ],
        },
        {
            id: "composta",
            title: "Hacer Composta",
            emoji: "🌱",
            description: "Los 4 pasos para hacer composta",
            color: "#606C38",
            questions: [
                {
                    id: "sc-12",
                    levelId: "composta",
                    questionType: "order_steps",
                    questionText: "Ordena los pasos para hacer una composta",
                    points: 10,
                    steps: [
                        "Cubre la base de una caja de madera con ramas y hojas",
                        "Coloca restos de comida en trocitos y cubre con otra capa de hojas, ramas y pasto",
                        "Humedece el contenido con un poco de agua y espera de 6 a 8 semanas. Dale vueltas cada tres días",
                        "El contenido de la caja se oscurecerá. Viértelo en las raíces de las plantas para ayudarlas a crecer",
                    ],
                },
                {
                    id: "sc-13",
                    levelId: "composta",
                    questionType: "true_false",
                    questionText: "La composta se prepara con restos de comida y hojas",
                    points: 10,
                    correctAnswer: "Verdadero",
                },
                {
                    id: "sc-14",
                    levelId: "composta",
                    questionType: "true_false",
                    questionText: "La composta está lista en 1 día",
                    points: 10,
                    correctAnswer: "Falso",
                    hint: "La composta tarda de 6 a 8 semanas en estar lista",
                },
                {
                    id: "sc-15",
                    levelId: "composta",
                    questionType: "multiple_choice",
                    questionText: "¿Para qué sirve la composta terminada?",
                    points: 10,
                    options: [
                        "Se vierte en las raíces de las plantas como abono para ayudarlas a crecer",
                        "Se tira a la basura",
                        "Se usa para construir casas",
                        "Se come como alimento",
                    ],
                    correctAnswer: "Se vierte en las raíces de las plantas como abono para ayudarlas a crecer",
                },
                {
                    id: "sc-16",
                    levelId: "composta",
                    questionType: "multiple_choice",
                    questionText: "¿Cada cuánto tiempo se le deben dar vueltas a la mezcla de la composta?",
                    points: 10,
                    options: [
                        "Cada tres días",
                        "Cada hora",
                        "Nunca",
                        "Una vez al mes",
                    ],
                    correctAnswer: "Cada tres días",
                },
            ],
        },
        {
            id: "heroe-villano",
            title: "Héroe o Villano",
            emoji: "🦸",
            description: "Acciones responsables vs irresponsables",
            color: "#E76F51",
            questions: [
                {
                    id: "sc-17",
                    levelId: "heroe-villano",
                    questionType: "classify",
                    questionText: "¿Esta acción es responsable o irresponsable con el ambiente?",
                    points: 10,
                    categories: [
                        { id: "responsable", label: "Responsable", emoji: "✅", color: "#2A9D8F" },
                        { id: "irresponsable", label: "Irresponsable", emoji: "❌", color: "#E76F51" },
                    ],
                    classifyItems: [
                        { text: "Cerrar la llave del agua mientras me cepillo los dientes", emoji: "🚿", correctCategoryId: "responsable" },
                        { text: "Quemar basura en lugar de reciclarla", emoji: "🔥", correctCategoryId: "irresponsable" },
                        { text: "Dejar los dispositivos eléctricos enchufados cuando no se usan", emoji: "🔌", correctCategoryId: "irresponsable" },
                        { text: "Elaborar composta con restos de comida para usarla como abono", emoji: "🌱", correctCategoryId: "responsable" },
                        { text: "Consumir productos desechables y de un solo uso", emoji: "🥤", correctCategoryId: "irresponsable" },
                        { text: "Separar la basura en orgánica e inorgánica", emoji: "🗑️", correctCategoryId: "responsable" },
                    ],
                },
                {
                    id: "sc-18",
                    levelId: "heroe-villano",
                    questionType: "true_false",
                    questionText: "Quemar basura es una práctica responsable con el ambiente",
                    points: 10,
                    correctAnswer: "Falso",
                    hint: "Quemar basura genera humo y gases tóxicos que contaminan el aire",
                },
                {
                    id: "sc-19",
                    levelId: "heroe-villano",
                    questionType: "multiple_choice",
                    questionText: "¿Qué contamina el mal manejo de la basura?",
                    points: 10,
                    options: [
                        "El aire, el agua y el suelo",
                        "Solo el aire",
                        "Solo el agua",
                        "Nada, no contamina",
                    ],
                    correctAnswer: "El aire, el agua y el suelo",
                },
                {
                    id: "sc-20",
                    levelId: "heroe-villano",
                    questionType: "true_false",
                    questionText: "Cerrar la llave del agua mientras nos lavamos los dientes es una acción responsable",
                    points: 10,
                    correctAnswer: "Verdadero",
                },
                {
                    id: "sc-21",
                    levelId: "heroe-villano",
                    questionType: "multiple_choice",
                    questionText: "¿Dónde se produce la basura?",
                    points: 10,
                    options: [
                        "En nuestras casas, en la calle, y en las fábricas",
                        "Solo en las fábricas",
                        "Solo en las escuelas",
                        "Solo en los basureros",
                    ],
                    correctAnswer: "En nuestras casas, en la calle, y en las fábricas",
                },
            ],
        },
    ],
};
