import type { SubjectWorld } from "./types";

export const SPANISH_WORLD: SubjectWorld = {
    id: "spanish",
    title: "Español",
    emoji: "📝",
    color: "#E9C46A",
    description: "Nota informativa y medios de comunicación",
    levels: [
        {
            id: "nota-informativa",
            title: "La Nota Informativa",
            emoji: "📰",
            description: "Partes, características y estructura",
            color: "#E9C46A",
            questions: [
                {
                    id: "sp-01",
                    levelId: "nota-informativa",
                    questionType: "multiple_choice",
                    questionText: "¿Qué son las notas informativas?",
                    points: 10,
                    options: [
                        "Textos que comunican hechos relevantes para una comunidad",
                        "Cuentos que narran historias de ficción",
                        "Instrucciones para hacer manualidades",
                        "Poemas que expresan sentimientos",
                    ],
                    correctAnswer: "Textos que comunican hechos relevantes para una comunidad",
                },
                {
                    id: "sp-02",
                    levelId: "nota-informativa",
                    questionType: "multiple_choice",
                    questionText: "¿Dónde se publican las notas informativas?",
                    points: 10,
                    options: [
                        "En periódicos, revistas y blogs",
                        "Solo en libros de texto",
                        "Solo en la televisión",
                        "En cuadernos escolares",
                    ],
                    correctAnswer: "En periódicos, revistas y blogs",
                },
                {
                    id: "sp-03",
                    levelId: "nota-informativa",
                    questionType: "match",
                    questionText: "Relaciona cada parte de la nota informativa con su función",
                    points: 10,
                    matchPairs: [
                        { left: "Título", right: "Menciona lo más importante de la nota" },
                        { left: "Introducción", right: "Amplía la información del título" },
                        { left: "Cuerpo", right: "Presenta los hechos: qué sucedió, quiénes participaron" },
                        { left: "Recursos gráficos", right: "Fotografías, esquemas o gráficas que acompañan" },
                    ],
                },
                {
                    id: "sp-04",
                    levelId: "nota-informativa",
                    questionType: "true_false",
                    questionText: "El título de una nota informativa debe ser llamativo para el lector",
                    points: 10,
                    correctAnswer: "Verdadero",
                },
                {
                    id: "sp-05",
                    levelId: "nota-informativa",
                    questionType: "true_false",
                    questionText: "Las notas informativas reportan historias inventadas",
                    points: 10,
                    correctAnswer: "Falso",
                    hint: "Las notas informativas reportan sucesos reales",
                },
                {
                    id: "sp-06",
                    levelId: "nota-informativa",
                    questionType: "multiple_choice",
                    questionText: "¿Cuáles pueden ser fuentes de información de una nota informativa?",
                    points: 10,
                    options: [
                        "Documentos, personas que vieron o fueron parte del hecho, fotografías o videos",
                        "Solo libros de la biblioteca",
                        "Solo lo que dice el maestro",
                        "Historias de amigos",
                    ],
                    correctAnswer: "Documentos, personas que vieron o fueron parte del hecho, fotografías o videos",
                },
                {
                    id: "sp-07",
                    levelId: "nota-informativa",
                    questionType: "true_false",
                    questionText: "El cuerpo de la nota informativa menciona quiénes participaron, cuándo y dónde ocurrió",
                    points: 10,
                    correctAnswer: "Verdadero",
                },
            ],
        },
        {
            id: "medios-comunicacion",
            title: "Medios de Comunicación",
            emoji: "📱",
            description: "Medios impresos vs digitales",
            color: "#457B9D",
            questions: [
                {
                    id: "sp-08",
                    levelId: "medios-comunicacion",
                    questionType: "classify",
                    questionText: "Clasifica cada medio como impreso o digital",
                    points: 10,
                    categories: [
                        { id: "impreso", label: "Impreso", emoji: "📰", color: "#E9C46A" },
                        { id: "digital", label: "Digital", emoji: "💻", color: "#457B9D" },
                    ],
                    classifyItems: [
                        { text: "Periódico", emoji: "📰", correctCategoryId: "impreso" },
                        { text: "Blog en internet", emoji: "💻", correctCategoryId: "digital" },
                        { text: "Revista", emoji: "📕", correctCategoryId: "impreso" },
                        { text: "Página web de noticias", emoji: "🌐", correctCategoryId: "digital" },
                        { text: "Folleto", emoji: "📄", correctCategoryId: "impreso" },
                        { text: "Noticiero en línea", emoji: "📺", correctCategoryId: "digital" },
                    ],
                },
                {
                    id: "sp-09",
                    levelId: "medios-comunicacion",
                    questionType: "true_false",
                    questionText: "Los medios impresos usan tinta y papel para publicarse",
                    points: 10,
                    correctAnswer: "Verdadero",
                },
                {
                    id: "sp-10",
                    levelId: "medios-comunicacion",
                    questionType: "true_false",
                    questionText: "Los medios digitales necesitan electricidad e internet para consultarse",
                    points: 10,
                    correctAnswer: "Verdadero",
                },
                {
                    id: "sp-11",
                    levelId: "medios-comunicacion",
                    questionType: "multiple_choice",
                    questionText: "¿Qué ventaja tienen los medios digitales sobre los impresos?",
                    points: 10,
                    options: [
                        "Pueden actualizarse de manera inmediata",
                        "Son más baratos de producir siempre",
                        "No necesitan ningún dispositivo",
                        "Solo pueden verse en una fecha fija",
                    ],
                    correctAnswer: "Pueden actualizarse de manera inmediata",
                },
                {
                    id: "sp-12",
                    levelId: "medios-comunicacion",
                    questionType: "multiple_choice",
                    questionText: "¿Qué pasa con un periódico impreso si tiene un error?",
                    points: 10,
                    options: [
                        "Hay que esperar al siguiente día para corregirlo",
                        "Se corrige inmediatamente",
                        "Se borra automáticamente",
                        "No importa el error",
                    ],
                    correctAnswer: "Hay que esperar al siguiente día para corregirlo",
                },
                {
                    id: "sp-13",
                    levelId: "medios-comunicacion",
                    questionType: "true_false",
                    questionText: "Los medios impresos se publican en una fecha fija y se venden en puestos de periódicos",
                    points: 10,
                    correctAnswer: "Verdadero",
                },
                {
                    id: "sp-14",
                    levelId: "medios-comunicacion",
                    questionType: "multiple_choice",
                    questionText: "¿Cuál es un ejemplo de medio de información digital?",
                    points: 10,
                    options: [
                        "Un blog en internet",
                        "Una revista de papel",
                        "Un libro de la biblioteca",
                        "Un cuaderno escolar",
                    ],
                    correctAnswer: "Un blog en internet",
                },
            ],
        },
    ],
};
